// <auto-generated />
using System;
using Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Datos.Migrations
{
    [DbContext(typeof(CasetaContext))]
    [Migration("20220210234543_ConfiguracionInicial")]
    partial class ConfiguracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dominio.Caseta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CasetaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("BActivo")
                        .HasMaxLength(15)
                        .HasColumnType("bit");

                    b.Property<int?>("CasetaId")
                        .HasColumnType("int")
                        .HasColumnName("CasetaId1");

                    b.Property<DateTime>("FechaAlta")
                        .HasMaxLength(250)
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEdita")
                        .HasMaxLength(15)
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaElimina")
                        .HasMaxLength(15)
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("CasetaId");

                    b.ToTable("Caseta", "catalogos");
                });

            modelBuilder.Entity("Dominio.Caseta", b =>
                {
                    b.HasOne("Dominio.Caseta", null)
                        .WithMany("Casetas")
                        .HasForeignKey("CasetaId");
                });

            modelBuilder.Entity("Dominio.Caseta", b =>
                {
                    b.Navigation("Casetas");
                });
#pragma warning restore 612, 618
        }
    }
}
